# Generated by Django 3.0.6 on 2020-05-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('poblacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
